### ISSUE TITLE
AttributeError: module 'typing' has no attribute '_SpecialForm'

### ISSUE THREAD

**Issue by Wonder1905** [PrateekMunjal/TorchAL#2]
HI, thanks for your work, I'm tryin to enable the framework, I installed the conda environment using the yaml file suggested and using https://github.com/PrateekMunjal/TorchAL/blob/master/instructions.txt , in both ways I'm getting the error:
``AttributeError: module 'typing' has no attribute '_SpecialForm'
``
I did exactly as said by instructions. any idea what is wrong?

Thanks again.

**Comment by PrateekMunjal** [comment]
Hi @BattashB,

Thanks for your interest in our work.

Apologies for the late reply. I am not sure what is going wrong with your setup. I even tried setting up another environment on my machine but unfortunately, I did not encounter the error you mentioned. If possible, can you please share what exact command is breaking your conda env?   
For your reference I am attaching the (pdf of ) jupyter notebook which showcases the successful installation of env (using yml file) and python, nvcc versions - please see if there is any mismatch with your system configuration.
<img width="688" alt="setup_env_versions" src="https://user-images.githubusercontent.com/7415240/180613160-5e31a7e0-29d1-4746-bf24-eca89b7a93a3.png">
[setup_env.pdf](https://github.com/PrateekMunjal/TorchAL/files/9174133/setup_env.pdf)
